### ISSUE TITLE
Regarding your organization

### ISSUE THREAD

**Issue by swagkarna** [r00t-3xp10it/redpill#3]
How to join your organization? @Suspicious-Shell-Activity ....

**Comment by r00t-3xp10it** [comment]
well ..
In the begging me and a group of friends have founded @Suspicious-Shell-Activity ..
But after a few years i have been left alone, and i have decided to allways carry the team name ..
After a few years later, more people have join the crew only to left me alone again ...

Currently the team its just me and and old menber that sometimes help me debug stuff!!!
but anyone are wellcome to join { * red hat stuff are forbiden * - doing harm to others in team name }

**Comment by swagkarna** [comment]
Bruh ok fine i am intrested to join in your group ...Send an invite to me...And i promise i dont involve in any type of illegal activities and i am responsible for it
