### ISSUE TITLE
No Longer Works - WinDefend Patched

### ISSUE THREAD

**Issue by swagkarna** [r00t-3xp10it/redpill#5]
This command  `.\DisableDefender.ps1 -Action Stop -ServiceName WinDefend`..No longer will work.Microsoft has patched the bug....When you run this you will get `access denied` and  security alert will be produced ...Either remove it from your repo or do mention in `readme` Check my repo to know more https://github.com/swagkarna/Defeat-Defender

**Comment by r00t-3xp10it** [comment]
yap i have knotests that also a few days ago (working in bypass tamper protection) ..

**Comment by swagkarna** [comment]
> yap i have knotests that also a few days ago (working in bypass tamper protection) ..
> I have added checks to this module ... But iam going to maitain it because attacker migth
> enconter unpatched versions of windefend or meenwhile i migth find another way to bypass this ...
> 
> ![err](https://user-images.githubusercontent.com/23490060/120073993-90153800-c092-11eb-9d39-639d026c797c.png)

Thnks i am also working on "Defeat-Defender v2"where  i will again defeat defender and bypass tamper protection

**Comment by r00t-3xp10it** [comment]
```powershell
.\redpill -GetLogs Yara
```
![err](https://user-images.githubusercontent.com/23490060/120091713-aa3c2e00-c105-11eb-9403-ed251d169542.png)

**Comment by r00t-3xp10it** [comment]
bypass: https://gist.github.com/r00t-3xp10it/6f10741153c103995d2fd1a2c82324e1

**Comment by swagkarna** [comment]
404 page not found

**Comment by r00t-3xp10it** [comment]
instructions: https://github.com/r00t-3xp10it/redpill/tree/main/utils/DWD
