### ISSUE TITLE
DisableAV - deprecated - Patched

### ISSUE THREAD

**Issue by r00t-3xp10it** [r00t-3xp10it/redpill#6]
Note-To-Self: [@redpill - DisableDefender.ps1](https://github.com/r00t-3xp10it/redpill/blob/main/bin/DisableDefender.ps1) module its deprecated ..<br />Recent Windows Defender release have patched to vulnerability ..

A new version of <b><i>'DisableDefender.ps1'</i></b> will be available soon to address this issue!

**Comment by swagkarna** [comment]
> Note-To-Self: [@redpill - DisableDefender.ps1](https://github.com/r00t-3xp10it/redpill/blob/main/bin/DisableDefender.ps1) module its deprecated ..
> Recent Windows Defender release have patched to vulnerability ..
> 
> A new version of 'DisableDefender.ps1' will be available soon to address this issue!

Bruh Defeat-Defender project is not dead still we can disable windefend service using NSudo see my msg on twitter
