### ISSUE TITLE
Cooperation

### ISSUE THREAD

**Issue by xiaoyuer0408** [r00t-3xp10it/redpill#8]
Hello sir, I would like to hire you to develop a software, do you have time, if you are interested, please also give me the contact information

**Comment by r00t-3xp10it** [comment]
tell me more

**Comment by Chengxinhezuo** [comment]
> tell me more 

Hello, I am Chinese, and I want to find hackers to hack into the gambling platform to change data and make money together. My email address is sxosxo7@gmail.com, looking forward to your reply and cooperation
